### ISSUE TITLE
ETQ OPS, je mets à disposition un sous-réseau privé de classe C

### ISSUE THREAD

**Issue by lpiot** [SocialGouv/UDD#1]
Ce sous-réseau est utilisé par les _VMs_ des _clusters_ `Kubernetes`et les _reverse-proxies_ en amont.
Les _reverse-proxies_ doivent disposer d'une translation d'adresses (_NAT_) vers 2 à 4 IP publiques.

**Comment by igorrenquin** [comment]
Une demie classe C est disponible (IP min: 130 - IP max: 254).
- NAT de IP: 134 à 164
- No NAT de IP: 166 à 254

**Comment by lpiot** [comment]
\o/
Tu me pousses les IPs ailleurs ?

**Comment by igorrenquin** [comment]
Toutes les actions sont terminées
