### ISSUE TITLE
ETQ DevOps, je déploie un Gitlab dédié à l'incubateur sur K8S

### ISSUE THREAD

**Issue by lpiot** [SocialGouv/UDD#12]
L'idée est de disposer d'un `Gitlab` version _core_ déployé sur le _cluster_ `K8S`.
* [ ] installation de `Gitlab`
* [ ] configuration de `Gitlab`
* [ ] configuration de `Gitlab-CI`
* [ ] configuration de la _registry_ `Docker`
* [ ] configuration des _runners_

**Comment by lpiot** [comment]
@douglasduteil challenge la nécessité d'embarquer un `Gitlab` _on-premise_, là où `GitHub` + `Travis-CI` semblent suffire dans la plupart des cas.  
Qu'en pensez-vous, @revolunet @EricH34 ?

**Comment by revolunet** [comment]
Hey ☀️

Notre premier objectif c'est de pouvoir déployer des environnements de dev/recette à la demande.

donc si GitHub+Travis font le job côté CI, on peut se focus sur la partie k8s et déjà fournir la plateforme de destination de ces environnements, la gestion des vhosts+SSL, monitoring...

Et on pourra toujours "migrer" certains projets sur un GitLab interne si besoin ?

**Comment by lpiot** [comment]
Je vais POCer dans la semaine la pertinence de `Travis-CI` pour nos besoins et je vous fais signe.
On peut considérer que cette _issue_ passe dans mon camp.

**Comment by lpiot** [comment]
L'ennui de la `docker registry` c'est que c'est pas terrible.
En plus, ça pourrait être pertinent de proposer un gestionnaire d'_artefacts_ plus large que juste les `docker`images.
Je raffine la proposition et je reviens vers vous.
