### ISSUE TITLE
Docker/Kube + logging best practices

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/UDD#18]
Quelles seraient les best practices pour la gestion des logs ?

Par exemple pour nos applis en NodeJS dockerisées.

 - quelles lib de logging utiliser ?
 - comment récupérer/centraliser les logs ?
 - quel outil pour consulter les logs ? kibana ?

**Comment by igorrenquin** [comment]
Est-ce que configurer tous les composants pour envoyer dans un SYSLOG au niveau de container puis ensuite les envoyer les informations du SYSLOG dans Elastic Search pourrait-être une option?

```
graph TD;
 A[APPLI]-->B[SYSLOG];
 B[SYSLOG]-->C[ELASTIC S];
 C[ESLASTIC S]-->D[KIBANA];
```
