### ISSUE TITLE
ETQ OPS, je réserve les IPs v4 d'un sous-réseau de classe B

### ISSUE THREAD

**Issue by lpiot** [SocialGouv/UDD#2]
Afin d'éviter toute collision et/ou conflit de routage avec une configuration réseau existante, les _clusters_ `Kubernetes` doivent disposer des adresses `IP v4` d'un sous-réseau de **classe B** dédié.

**Comment by igorrenquin** [comment]
Vue avec la PROD.
Si la classe B n'est pas utilisée hors de Kubernetes alors on peut choisir celle que l'on souhaite.

**Comment by lpiot** [comment]
\o/
