### ISSUE TITLE
ETQ OPS, je provisionne les VMs du cluster Kubernetes #1

### ISSUE THREAD

**Issue by lpiot** [SocialGouv/UDD#3]
Les 8 _VMs_ présentes les caractéristiques suivantes :
* 3 _VMs_ _master_
  * avec chacune 2 vCPUs et 4 Go de RAM
  * portées par des hyperviseurs différents (règle d'anti-affinité)
* 3 _VMs_ _minion_
  * avec chacune 4 vCPUs et 8 Go de RAM
  * portées par des hyperviseurs différents (règle d'anti-affinité)
* 2 VMs _reverse-proxies_
  * avec chacune 2 vCPUs et 4 Go de RAM
  * portées par des hyperviseurs différents (règle d'anti-affinité)
  * avec `NAT`tage vers des IP publiques

L'ensemble de ces _VMs_ partagent les caractéristiques suivantes :
* elles doivent pouvoir sortir sur Internet (en tant que client)
* elles sont sur base `CentOS 7.5 3.10.0` publique
* on dispose de leur mot de passe `root`

La taille des disques peut être relativement standard :
* 20 Go d'espace disque pour un disque système
* 20 Go d'espace disque pour un disque _data_
* [x] @lpiot affine ce point avec @igorrenquin.

**Comment by igorrenquin** [comment]
##Déploiement des 2 VMs reverse-proxies

[x] 2 vCPUs et 4 Go de RAM | Datastore 17, 16
[x] ajout d'un HDD de 20Gb sur chaque VM | Datastore 17, 16
[x] montage du disque dans la VM /data 
[ ] portées par des hyperviseurs différents (règle d'anti-affinité)
[x] avec NATtage vers des IP publiques

RP1 164.131.131.241 ou IP interne XX.XXX.XXX.151
RP2 164.131.131.242 ou IP interne XX.XXX.XXX.152

##Déploiement des 3 VMs master

[x] 2 vCPUs et 4 Go de RAM | Datastore 17, 16, 15
[x] ajout d'un HDD de 20Gb sur chaque VM | Datastore 17, 16, 15
[ ] portées par des hyperviseurs différents (règle d'anti-affinité)

K8S-1-MS1 IP interne XX.XXX.XXX.166
K8S-1-MS2 IP interne XX.XXX.XXX.167
K8S-1-MS3 IP interne XX.XXX.XXX.168

##Déploiement des 3 VMs minions

[x] 4 vCPUs et 8 Go de RAM | Datastore 17, 16, 15
[x] ajout d'un HDD de 20Gb sur chaque VM | Datastore 17, 16, 15
[ ] portées par des hyperviseurs différents (règle d'anti-affinité)

K8S-1-MIN1 IP interne XX.XXX.XXX.169
K8S-1-MIN2 IP interne XX.XXX.XXX.170
K8S-1-MIN3 IP interne XX.XXX.XXX.171

-------
#Création d'un template de VM pour l'UDD

[x] Install niveau ''infrastructure'' de CentOS 7.5 1804
[x] Suppression des open-vm-tool installé par défaut
[x] Transformation de la VM en template VMware

```sh
# yum remove open-vm-tools
```
[x] Installation des VMware Tools
```sh
#mkdir /mnt/cdrom
#mount /dev/cdrom /mnt/cdrom
#ls /mnt/cdrom
#tar xzvf /mnt/cdrom/VMwareTools-x.x.x-xxxx.tar.gz -C /tmp/
#cd /tmp/vmware-tools-distrib/
#./vmware-install.pl -f
```
[x] Mise à jour de l'O.S.
```sh
#yum update
```


-------
Création d'une partition

```sh
#fdisk -l
#fdisk /dev/sdb
- n (create partition)
- p (primary)
- 1 (partition number)
- w

#mkfs.ext4 /dev/sdb1
#cd /
#mkdir /data
#mount /dev/sdb1 /data
```

```sh
#vi /etc/fstab
/dev/sdb1 /data ext4 defaults 0 0
```

**Comment by igorrenquin** [comment]
Il me reste à voir pour les règles de non affinités sur les serveurs.
Rien de bloquant pour commencer le déploiement des composants

**Comment by igorrenquin** [comment]
Est-ce que je demande l'activation du HA en plus des régles d'anti-affinité si oui sur quoi?
RP?
K8s Master?
K8s Minions?

**Comment by lpiot** [comment]
Côté `NGinx`, oui, c'est une bonne idée.
Côté `K8s`, on va attendre d'avoir fait les tests de résilience, etc.

**Comment by lpiot** [comment]
> Il me reste à voir pour les règles de non affinités sur les serveurs.
> Rien de bloquant pour commencer le déploiement des composants

Ca en est où @igorrenquin ?  
C'est finalisé les règles d'anti-affinité ? Sinon, on peut peut-être externaliser cette tâche là dans une _issue_ dédiée

**Comment by igorrenquin** [comment]
Les règles ne sont pas encore implémentées. Par contre j'ai l'accord pour les réaliser.
OK pour ta proposition d'externaliser cette action dans une autre issue.

**Comment by igorrenquin** [comment]
Ouverture de l'issue #17  pour les régles anti-affinité OK
