### ISSUE TITLE
ETQ resp. plateforme, je choisi 2 noms de domaine pour exposer les applications en PROD / en TEST

### ISSUE THREAD

**Issue by lpiot** [SocialGouv/UDD#4]
L'ensemble des applications exposées sur le _cluster_ `Kubernetes` est accessible via un nom de domaine donné :
`*.???.social.gouv.fr`

* Quelle valeur pour `???` pour la PROD ?
* Quelle valeur pour `???` pour les TESTs ?

**Comment by revolunet** [comment]
NB : actuellement `incubateur.social.gouv.fr` et `num.social.gouv.fr` pointent sur notre RP

**Comment by igorrenquin** [comment]
*.factory.social.vouv.fr
*.factory-test.social.gouv.fr

**Comment by igorrenquin** [comment]
Ce n'était qu'une proposition de ma part.

**Comment by revolunet** [comment]
yet another proposal :
 - prod : incubateur.social.gouv.fr
 - dev/recette : factory.social.gouv.fr

**Comment by igorrenquin** [comment]
> yet another proposal :
> 
> * prod : incubateur.social.gouv.fr
> * dev/recette : factory.social.gouv.fr

Comment envisage tu le transfert du workload DNS de *.incubateur.social.gouv.fr de l'ancien RP vers le nouveau sans coupure de service?

**Comment by revolunet** [comment]
en fait actuellement on utilise que `num.social.gouv.fr`. donc on pourrait :
 - faire des redirections une fois les services migrés
 - migrer le DNS
 - supprimer le RP actuel

**Comment by igorrenquin** [comment]
OK

**Comment by lpiot** [comment]
Oui, la question de la bascule `DNS` nécessite juste que les _reverse-proxies_ soient correctement configurés.
Mais ça peut être décorellé de la bascule des services applicatifs eux-mêmes.
