### ISSUE TITLE
ETQ OPS, j'ajoute l'entrée DNS pour le sous-domaine de PROD / TESTs

### ISSUE THREAD

**Issue by lpiot** [SocialGouv/UDD#5]
En attente de #4 
Des entrées _DNS_ font correspondre :
* les noms de domaine choisis dans #4
* et l'adresse IP publique de la vIP pointant vers les _reverse-proxies_.

**Comment by igorrenquin** [comment]
IP publique de la VIP 164.131.131.240
RP1 Nginx : 164.131.131.241
RP2 Nginx : 164.131.131.242

**Comment by igorrenquin** [comment]
Demande de mise à jour du DNS public du MCAS intiée.


Entrée                                | Type   enregistrement | IP de   destination
-----------------------------|:------------------------:|:---------------------:
*.incubateur.social.gouv.fr | A                                  | 164.131.131.240
*.factory.social.gouv.fr       | A                                  | 164.131.131.240

**Comment by igorrenquin** [comment]
La mise à jour du DNS est terminée.
